version: "3.4"

services:
  dev-app:
    env_file: .env
    ports:
      - "5000:5000"
    build: 
      context: .
      target: development
    volumes:
      - "./:/app"
  prod-app:
    env_file: .env
    ports:
      - "5000:8000"
    build:
      context: .
      target: production
  test:
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      TRELLO_API_BASE_URL: ${TRELLO_API_BASE_URL}
      TRELLO_KEY: ${TRELLO_KEY}
      TRELLO_TOKEN: ${TRELLO_TOKEN}
      TRELLO_BOARD_ID: ${TRELLO_BOARD_ID}
    build:
      context: .
      target: test